
development:
  adapter: postgresql
  encoding: unicode
  database: elite_rails_graphql_development
  pool: 5
  username: chrislmauldin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: elite_rails_graphql_test
  pool: 5
  username: chrislmauldin
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: elite_rails_graphql_production
  pool: 5
  username: chrislmauldin
  password:
