# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65e6a084e475f66285648d59313b2ef3c58746f332992ee859ee55e613c53c5a3dafc4d9ab400d4ab07372f4942370ba10d807a9b9355dcfbaa563e6b9657f05

test:
  secret_key_base: 7be0f7161c6b7d16ebfb37fbc79e34ee9fa4e51048c93bd5279db976e4cd5b5147ac957d6888b72c4b169284ebe0af6715d495fbb5b14e792c2ca67dd1b157f8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
